# Generated by Django 4.1.5 on 2023-01-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CNAB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=1)),
                ("descricao", models.CharField(max_length=30)),
                ("data", models.DateField()),
                ("valor", models.IntegerField()),
                ("cpf", models.CharField(max_length=11)),
                ("cartao", models.CharField(max_length=12)),
                ("hora", models.TimeField()),
                ("dono_loja", models.CharField(max_length=14)),
                ("nome_loja", models.CharField(max_length=19)),
                ("natureza", models.CharField(max_length=7)),
                ("sinal", models.CharField(max_length=1)),
            ],
        ),
    ]
